name: Lint

on: 
  push:
    branches:
      - master
<<<<<<< HEAD
  pull_request:
    branches: []
=======
      - meta/workflows
  pull_request:
    branches: 
      - '*'
>>>>>>> origin/public-refactor

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

<<<<<<< HEAD

=======
>>>>>>> origin/public-refactor
      - name: Install Deps
        run: |
          pip install -r requirements.txt
      
<<<<<<< HEAD
      - name: Run Pyright
        uses: jakebailey/pyright-action@v1

=======
>>>>>>> origin/public-refactor
      - name: black
        run: |
          black . --config pyproject.toml --check

      - name: isort
        uses: isort/isort-action@v1
        with:
            requirements-files: "requirements.txt"
