name: Call a reusable workflow

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  lint:
    uses: kurzgesagt-in-a-nutshell/.github/.github/workflows/lint-python.yml@v1
