name: Lint Python

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  lint:
    uses: kurzgesagt-in-a-nutshell/.github/.github/workflows/python-lint.yml@main
