name: Lint Python

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  lint:
    uses: kurzgesagt-in-a-nutshell/.github/.github/workflows/python-lint.yml@main
  license-check:
    uses: kurzgesagt-in-a-nutshell/.github/.github/workflows/license-check.yml@license-check
    with:
      config-path: ${{ github.action_repository }}/.github/workflows/license-check-config.json
      
